/*
 * Copyright (c) 2016-2019 Newracom, Inc.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _NRC_VENDOR_H_
#define _NRC_VENDOR_H_

#define OUI_NRC								0xFCFFAA
#define NRC_OUI_SUBCMD_ANNOUNCE1			0xF0
#define NRC_OUI_SUBCMD_ANNOUNCE2			0xF1
#define NRC_OUI_SUBCMD_ANNOUNCE3			0xF2
#define NRC_OUI_SUBCMD_ANNOUNCE4			0xF3
#define NRC_OUI_SUBCMD_ANNOUNCE5			0xF4

enum nrc_vendor_event {
	NRC_VENDOR_EVENT_ANNOUNCE = 0,
	NUM_VENDOR_EVENT,
	MAX_VENDOR_EVENT = NUM_VENDOR_EVENT - 1
};

enum nrc_vendor_attributes {
	NRC_VENDOR_ATTR_DATA = 0,
	NUM_VENDOR_ATTR,
	MAX_VENDOR_ATTR = NUM_VENDOR_ATTR - 1
};

#endif /* _NRC_VENDOR_H_ */
